quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/quizzy
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.hibernate-orm.database.generation=update

mp.jwt.verify.issuer=https://securetoken.google.com/quizzy-allavin
mp.jwt.verify.publickey.location=META-INF/resources/key.pem