quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/quizzy
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.hibernate-orm.database.generation=update

quarkus.http.cors=true
%dev.quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.headers=Content-Type,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Authorization
%dev.quarkus.http.cors.exposed-headers=Location

mp.jwt.verify.issuer=https://securetoken.google.com/quizzy-allavin
mp.jwt.verify.publickey.location=https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com